### ISSUE TITLE
In-plugin parallelization on directory targets

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/python-chrisapp-template#1]

**Comment by jennydaman** [comment]
Hey @rudolphpienaar I've made changes and added features to `chris_plugin.PathMapper`, does this address what you want?

Overview: https://github.com/FNNDSC/chris_plugin/releases/tag/v0.0.16
Documentation: https://fnndsc.github.io/chris_plugin/chris_plugin.html#PathMapper.dir_mapper_shallow
Code examples: https://github.com/FNNDSC/chris_plugin/blob/0af66afff7da257b113b1b97d8137246d512712b/chris_plugin/tests/test_mapper.py#L66-L93

**Comment by rudolphpienaar** [comment]
I'll take a look!
